export const REQUEST_SERVERS = 'REQUEST_SERVERS';
export const RECEIVE_SERVERS = 'RECEIVE_SERVERS';

export const RECEIVE_UPLOADED_CONFIG = 'RECEIVE_UPLOADED_CONFIG';
export const CONFIG_DELETED = 'CONFIG_DELETED';

export const SERVER_LOADING_START = 'SERVER_LOADING_START';
export const SERVER_LOADING_STOP = 'SERVER_LOADING_STOP';
export const SERVER_STARTED = 'SERVER_STARTED';

export const SERVER_STOPPED = 'SERVER_STOPPED';
export const SERVER_OP_ERROR = 'SERVER_OP_ERROR';

export const REQUEST_LOGS = 'REQUEST_LOGS';
export const RECEIVE_LOGS = 'RECEIVE_LOGS';
export const REQUEST_LOG = 'REQUEST_LOG';
export const RECEIVE_LOG = 'RECEIVE_LOG';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
